### PR TITLE
Refactor game ids, to support China properly

### LINKED ISSUE #15: China diablo3 fails to install
**Describe the bug**
Regarding to 1.1.0 update, almost everything work fine but I found an issue with diablo3.
Probably because of unknown id for `d3cn`. Someone from China that have d3cn has to check result of his `backend_client.get_owned_games()` to find this unknown id.

**To Reproduce**
1. Log in with china account that have no diablo3 installed on local computer
2. Click Install
3. See this in battlenet
Screenshot 2020-03-20 at 11 52 41

**Logs**

```
2020-03-20 20:47:37,635 - root - INFO - Adding ? 暗黑破壞神III to installed games
2020-03-20 20:47:37,641 - root - DEBUG - Detected installation begin
2020-03-20 20:47:37,641 - root - INFO - Changing game ? state to LocalGameState.None_
2020-03-20 20:47:37,641 - galaxy.api.jsonrpc - INFO - Sending notification: method=local_game_status_changed, params={'local_game': LocalGame(game_id='?', local_game_state=<LocalGameState.None_: 0>)}
2020-03-20 20:47:37,641 - galaxy.api.jsonrpc - DEBUG - Sending 125 bytes of data
```

### PR DESCRIPTION
**Pull request by bartok765**
Fixes #15 
Closes (supersedes) #19 

- [x] get_owned_games: send uid instead of blizzard_id (transition blizzard_id -> uid)
- [x] handle classic games
- [x] install
- [x] uninstall
- [x] launch
- [x] get_game_time
- [x] tests

### CODE REVIEW

**Comment by a358003542** [comment]
@bartok765 use the uid but not the origin blizzard_id is really a brave move. it is ture out the most of game can work right .  I am not quite sure about the details . maybe you can talk to the galaxy client official about the s2 and d3cn page shown problem.

**Comment by bartok765** [comment]
For record: https://github.com/bartok765/galaxy_blizzard_plugin/pull/19#issuecomment-643136631

**Comment by a358003542** [comment]
@bartok765 It is work correctly now. 
批注 2020-06-12 190656

But there is still gots some page elements shown failed issue. and now i can click to install or start the game. 
批注 2020-06-12 190657

That's my Galaxy Client log. Hope can help you.
[GalaxyClient.log](https://github.com/bartok765/galaxy_blizzard_plugin/files/4770436/GalaxyClient.log)

**Comment by bartok765** [comment]
looks like they've fixed it. So, merging!

**Pull request merged**
