### PR TITLE
fix install china diablo3 fails issue

### PR DESCRIPTION
**Pull request by a358003542**

### CODE REVIEW

**Comment by bartok765** [comment]
I was thinking about this change and would accept it, but I think there is one better solution. Especially if D4 will suffer for similar problem.

What if we send to galaxy `uid` instead of `blizzard_id` as a `game_id`? Looks like it more "unique" (uid=unique-id). 
Then, the only place we have to use `region` to match uid with game ids is `get_owned_games` method. Then, Galaxy will pass "uid" for `launch_game` or `install_game` and we don't need to worry about any id translation!

Drawback? Maybe migration? I'll check what will happen when a plugin will report completely different set of ids

**Comment by a358003542** [comment]
@bartok765 I am not familiar with the galaxy client inside details, Thanks all your works.

**Comment by bartok765** [comment]
I've checked what will happens when the plugin returns different set of game ids:
- games with old id disappear
- new one are coming into "recently added" Galaxy section

So if we change game ids into different, users will see those old games as "recently added games" once, just after the migration to new plugin version.

I think it is not so bad.

@elkangaroo @saitho @a358003542 
Do you think it is worth to changing `blizzard_id` to `uid` to identify blizzard game and simplify code with this one drawback described above?

Simplification of the code mean:
- do not need to translate blizzard_id (coming from blizzard api) to uid (used by launcher) to install/launch/other local operations
- better separation: `region` parameter (see this PR) not need to be passed to `definitions.py` and `local_client_base.py` via `plugin.py`

**Comment by saitho** [comment]
Sounds good. I don't think anyone will mind if the game appears as recenly added once.

**Comment by a358003542** [comment]
@bartok765 That change are good, but there are many places use the id parameter called by galaxy client, that is mean we need to create a branch and do many code rejustment and test.

**Comment by bartok765** [comment]
Ok, so the new branch is `id_refactor`. Feel free to create PRs for those changes:
- send uid in owned_games (`blizzard_id` -> `uid`) should be trivial
- cleanup for classic games
- support for local games -> opening & installing Blizzard games
- support for `get_game_time` and other possible methods
- `uninstall`
- anything else?

I cannot join before at the end of week unfortunately.

**Comment by a358003542** [comment]
@ Thanks, I will test in the evening.

**Comment by a358003542** [comment]
@bartok765 I have test it , all work fine  and the code looks more cleaner now, that's great, but there has two games are showed unknown game.  which is maybe not this plugin's problem , please check [this link](https://github.com/Ertego/gog-galaxy-itch.io/issues/5)

please check the image: 

批注 2020-06-11 211925


I have tested that good games  by install it or launch it ,  which is all ok. 

and I have check the `get_owned_games` return : 
```
return Game object [('wow', 'World of Warcraft'), ('d3cn', '暗黑破壞神III'), ('hs_beta', 'Hearthstone'), ('heroes', 'Heroes of the Storm'), ('prometheus', 'Overwatch'), ('s2', 'StarCraft II'), ('wow_classic', 'World of Warcraft Classic'), ('s1', 'StarCraft'), ('odin', 'Call of Duty: Modern Warfare')]
```

I have tested it by changed the game_title attrib ,  It's turn out not responsable to the galaxy page's shown issue.

I have reinstall my gog galaxy client , that's make no difference. so that's my conclusion:

I this the branch `id_refactor ` is fine, although the d3cn and the sc2 still has some shown issue. but we can wait maybe later the galaxy will fix it.

**Comment by a358003542** [comment]
This pull can now been closed.

**Comment by bartok765** [comment]
Huh, @a358003542 thanks for finding this problem with s2 and d3cn. I've the same, but I though it is problem with my setup or poor internet connection. Apparently a bug in GOG games database. I'll contact them.

**Comment by bartok765** [comment]
@a358003542 can you send your `GalaxyClient.log`? In mine there is some info about getting 404 to their endinpoints for s2

**Pull request closed without merging**
